//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDW.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DDW.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap addSymbolCursor {
            get {
                object obj = ResourceManager.GetObject("addSymbolCursor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] arrowDup {
            get {
                object obj = ResourceManager.GetObject("arrowDup", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] arrowMove {
            get {
                object obj = ResourceManager.GetObject("arrowMove", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] arrowMoveCenter {
            get {
                object obj = ResourceManager.GetObject("arrowMoveCenter", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] David_Sans {
            get {
                object obj = ResourceManager.GetObject("David_Sans", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] David_Sans_Condensed {
            get {
                object obj = ResourceManager.GetObject("David_Sans_Condensed", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap guideBoth {
            get {
                object obj = ResourceManager.GetObject("guideBoth", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap guideHorizontal {
            get {
                object obj = ResourceManager.GetObject("guideHorizontal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap guidePoint {
            get {
                object obj = ResourceManager.GetObject("guidePoint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap guideVertical {
            get {
                object obj = ResourceManager.GetObject("guideVertical", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] hand {
            get {
                object obj = ResourceManager.GetObject("hand", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] handClosed {
            get {
                object obj = ResourceManager.GetObject("handClosed", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap handle_anchor {
            get {
                object obj = ResourceManager.GetObject("handle_anchor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap handle_join {
            get {
                object obj = ResourceManager.GetObject("handle_join", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap handle_lock {
            get {
                object obj = ResourceManager.GetObject("handle_lock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap handle_magnet0 {
            get {
                object obj = ResourceManager.GetObject("handle_magnet0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap handle_magnet1 {
            get {
                object obj = ResourceManager.GetObject("handle_magnet1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap handle_magnet2 {
            get {
                object obj = ResourceManager.GetObject("handle_magnet2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap handle_magnet3 {
            get {
                object obj = ResourceManager.GetObject("handle_magnet3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap handle_pin {
            get {
                object obj = ResourceManager.GetObject("handle_pin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap handle_rotate {
            get {
                object obj = ResourceManager.GetObject("handle_rotate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap handle_rotate0 {
            get {
                object obj = ResourceManager.GetObject("handle_rotate0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap handle_rotate1 {
            get {
                object obj = ResourceManager.GetObject("handle_rotate1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap handle_rotate2 {
            get {
                object obj = ResourceManager.GetObject("handle_rotate2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap handle_rotate3 {
            get {
                object obj = ResourceManager.GetObject("handle_rotate3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap handle_spring0 {
            get {
                object obj = ResourceManager.GetObject("handle_spring0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap handle_spring1 {
            get {
                object obj = ResourceManager.GetObject("handle_spring1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap handle_spring2 {
            get {
                object obj = ResourceManager.GetObject("handle_spring2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap handle_spring3 {
            get {
                object obj = ResourceManager.GetObject("handle_spring3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap handle_square {
            get {
                object obj = ResourceManager.GetObject("handle_square", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap handle_squareSmall {
            get {
                object obj = ResourceManager.GetObject("handle_squareSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imageIcon {
            get {
                object obj = ResourceManager.GetObject("imageIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap iterateAbout {
            get {
                object obj = ResourceManager.GetObject("iterateAbout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] moveAllDir {
            get {
                object obj = ResourceManager.GetObject("moveAllDir", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] pf_ronda_seven {
            get {
                object obj = ResourceManager.GetObject("pf_ronda_seven", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] rectSelect {
            get {
                object obj = ResourceManager.GetObject("rectSelect", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] rotate {
            get {
                object obj = ResourceManager.GetObject("rotate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] stretchEW {
            get {
                object obj = ResourceManager.GetObject("stretchEW", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] stretchNE_SW {
            get {
                object obj = ResourceManager.GetObject("stretchNE_SW", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] stretchNS {
            get {
                object obj = ResourceManager.GetObject("stretchNS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] stretchNW_SE {
            get {
                object obj = ResourceManager.GetObject("stretchNW_SE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap update_d {
            get {
                object obj = ResourceManager.GetObject("update_d", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap update_n {
            get {
                object obj = ResourceManager.GetObject("update_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap update_o {
            get {
                object obj = ResourceManager.GetObject("update_o", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] zoomIn {
            get {
                object obj = ResourceManager.GetObject("zoomIn", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] zoomNone {
            get {
                object obj = ResourceManager.GetObject("zoomNone", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] zoomOut {
            get {
                object obj = ResourceManager.GetObject("zoomOut", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
